sudo: false

language: php

php: [7.1, 7.2, 7.3, 7.4]

before_script:
  - cd ./project
  - composer install
  - mkdir -p ./var

script:
  - composer run-script cover

after_script:
  - composer coveralls
