version: '3'
services:
    app:
        tty: true
        privileged: true
        stdin_open: true
        build:
            context: ../../../
            dockerfile: devops/build/app/Dockerfile
        volumes:
            - ./../../../project:/var/www/project
        links:
          - mysql
        env_file:
            - ../envs/local.env

    web:
        image: nginx
        volumes:
            - ./../../../project:/var/www/project
            - ./../../build/web/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        links:
            - app

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./../../../data:/var/lib/mysql
        restart: always
        env_file:
            - ../envs/local.env

